server:
  port: ${PORT:9090}
spring:
  application:
    name: product-api

  #Database
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: 123456
    url: jdbc:postgresql://localhost:5432/product-db

  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  # Logger configuration
  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug